### ISSUE TITLE
JSX syntax for merging props

### ISSUE THREAD

**Issue by sebmarkbage** [reactjs/react-future#7]
We need some nicer sugar for this new transferring pattern:

Transfer DOM props using merge strategy for className, style, aria, data. Ideally, this could just be a deepMerge all the time if className was an array:

``` javascript
var button = React.DOM.button(React.DOM.merge(
  this.props,
  {
    className: 'FancyButton',
    style: {
      backgroundColor: this.props.color,
      padding: 10,
      width: this.props.width - 10,
      height: this.props.height - 10
    },
    color: undefined,
    size: undefined
  }
));
```

Transfer props using deep merge:

``` javascript
var wideFancyButton = FancyButton(mergeDeep(
  this.props,
  {
    size: {
      width: 1000 // override width
    }
  }
));
```

Transfer props using flat merge:

``` javascript
var myButton = WideFancyButton(merge(
  this.props,
  {
    size: {
      width: 100, // will be overridden
      height: 100
    }
  }
));
```

Is it enough to just add syntax support for the deepMerge scenario? Flat merge is important for custom complex types in props.

**Comment by evenstensberg** [comment]
So cool looking back at old PR's/issues and see this implemented 😄
